var request = require('request');
var db = require('./helpers/db');
var Result = require('./models/result')(db.Sequelize, db.sequelize);
var reverseGeocode = require('./helpers/utils').reverseGeocode;

var data = [
    {location:"Adelaide, Australia", latency:264.05},
    {location:"Albany, United States", latency:11.185},
    {location:"Alblasserdam, Netherlands", latency:111.82},
    {location:"Albuquerque, United States", latency:71.974},
    {location:"Amsterdam, Netherlands", latency:93.463},
    {location:"Anchorage, United States", latency:117.695},
    {location:"Ankara, Turkey", latency:144.442},
    {location:"Arezzo, Italy", latency:151.877},
    {location:"Asheville, United States", latency:25.027},
    {location:"Athens, Greece", latency:134.238},
    {location:"Atlanta, United States", latency:14.888},
    {location:"Auckland, New Zealand", latency:204.273},
    {location:"Austin, United States", latency:46.378},
    {location:"Baltimore, United States", latency:8.434},
    {location:"Bangalore, India", latency:262.328},
    {location:"Bangkok, Thailand", latency:276.313},
    {location:"Barcelona, Spain", latency:100.271},
    {location:"Belfast, United Kingdom", latency:109.191},
    {location:"Bergen, Norway", latency:124.511},
    {location:"Berlin, Germany", latency:100.835},
    {location:"Bismarck, United States", latency:68.28},
    {location:"Bogota, Colombia", latency:82.846},
    {location:"Boston, United States", latency:12.184},
    {location:"Bratislava, Slovakia", latency:119.464},
    {location:"Brisbane, Australia", latency:237.981},
    {location:"Brno, Czech Republic", latency:111.085},
    {location:"Bruges, Belgium", latency:82.877},
    {location:"Brunswick, United States", latency:17.194},
    {location:"Brussels, Belgium", latency:98.026},
    {location:"Bucharest, Romania", latency:117.531},
    {location:"Budapest, Hungary", latency:127.291},
    {location:"Buenos Aires, Argentina", latency:157.024},
    {location:"Buffalo, United States", latency:38.616},
    {location:"Bursa, Turkey", latency:128.319},
    {location:"Cairo, Egypt", latency:150.829},
    {location:"Calgary, Canada", latency:96.441},
    {location:"Canberra, Australia", latency:225.773},
    {location:"Cape Town, South Africa", latency:227.589},
    {location:"Cardiff, United Kingdom", latency:92.773},
    {location:"Charlotte, United States", latency:19.576},
    {location:"Chennai, India", latency:254.039},
    {location:"Chicago, United States", latency:27.803},
    {location:"Chisinau, Moldova", latency:139.255},
    {location:"Christchurch, New Zealand", latency:232.246},
    {location:"Cincinnati, United States", latency:33.277},
    {location:"Cleveland, United States", latency:35.234},
    {location:"Colorado Springs, United States", latency:48.839},
    {location:"Columbus, United States", latency:35.817},
    {location:"Copenhagen, Denmark", latency:106.117},
    {location:"Coventry, United Kingdom", latency:86.497},
    {location:"Dagupan, Philippines", latency:251.398},
    {location:"Dallas, United States", latency:37.703},
    {location:"Dar es Salaam, Tanzania", latency:233.42},
    {location:"Denver, United States", latency:49.73},
    {location:"Des Moines, United States", latency:42.111},
    {location:"Detroit, United States", latency:25.461},
    {location:"Dhaka, Bangladesh", latency:291.682},
    {location:"Dronten, Netherlands", latency:99.406},
    {location:"Dubai, United Arab Emirates", latency:220.9},
    {location:"Dublin, Ireland", latency:128.182},
    {location:"Dusseldorf, Germany", latency:97.811},
    {location:"Edinburgh, United Kingdom", latency:91.281},
    {location:"Edmonton, Canada", latency:84.26},
    {location:"Fez, Morocco", latency:147.155},
    {location:"Frankfurt, Germany", latency:109.064},
    {location:"Fremont, United States", latency:75.452},
    {location:"Gdansk, Poland", latency:135.919},
    {location:"Geneva, Switzerland", latency:101.035},
    {location:"Gosport, United Kingdom", latency:95.903},
    {location:"Gothenburg, Sweden", latency:140.339},
    {location:"Green Bay, United States", latency:31.091},
    {location:"Groningen, Netherlands", latency:108.686},
    {location:"Guadalajara, Mexico", latency:76.746},
    {location:"Guatemala, Guatemala", latency:60.688},
    {location:"Halifax, Canada", latency:31.688},
    {location:"Hamburg, Germany", latency:109.501},
    {location:"Hamilton, Canada", latency:19.345},
    {location:"Hangzhou, China", latency:342.322},
    {location:"Hanoi, Vietnam", latency:260.039},
    {location:"Helsinki, Finland", latency:123.395},
    {location:"Heredia, Costa Rica", latency:69.395},
    {location:"Hong Kong, Hong Kong", latency:255.823},
    {location:"Honolulu, United States", latency:120.775},
    {location:"Houston, United States", latency:34.819},
    {location:"Hyderabad, India", latency:275.165},
    {location:"Indore, India", latency:320.848},
    {location:"Istanbul, Turkey", latency:138.441},
    {location:"Jackson, United States", latency:32.314},
    {location:"Jacksonville, United States", latency:19.722},
    {location:"Jakarta, Indonesia", latency:289.892},
    {location:"Joao Pessoa, Brazil", latency:102.635},
    {location:"Johannesburg, South Africa", latency:250.702},
    {location:"Kampala, Uganda", latency:272.968},
    {location:"Kansas City, United States", latency:33.319},
    {location:"Karaganda, Kazakhstan", latency:219.481},
    {location:"Kiev, Ukraine", latency:149.223},
    {location:"Knoxville, United States", latency:34.36},
    {location:"Ktis, Czech Republic", latency:106.659},
    {location:"La Ceiba, Honduras", latency:67.083},
    {location:"Lahore, Pakistan", latency:301.332},
    {location:"Las Vegas, United States", latency:82.989},
    {location:"Lausanne, Switzerland", latency:117.936},
    {location:"Liege, Belgium", latency:85.379},
    {location:"Lima, Peru", latency:101.373},
    {location:"Limassol, Cyprus", latency:146.265},
    {location:"Lisbon, Portugal", latency:116.86},
    {location:"Ljubljana, Slovenia", latency:122.969},
    {location:"London, United Kingdom", latency:78.903},
    {location:"Los Angeles, United States", latency:63.237},
    {location:"Louisville, United States", latency:36.636},
    {location:"Lugano, Switzerland", latency:128.204},
    {location:"Luxembourg, Luxembourg", latency:102.945},
    {location:"Madrid, Spain", latency:119.45},
    {location:"Maidstone, United Kingdom", latency:83.564},
    {location:"Malaysia, Malaysia", latency:295.4},
    {location:"Manchester, United Kingdom", latency:97.648},
    {location:"Manhattan, United States", latency:7.454},
    {location:"Manila, Philippines", latency:327.112},
    {location:"Medellin, Colombia", latency:88.69},
    {location:"Melbourne, Australia", latency:237.668},
    {location:"Mexico, Mexico", latency:59.739},
    {location:"Miami, United States", latency:26.697},
    {location:"Milan, Italy", latency:98.974},
    {location:"Minneapolis, United States", latency:32.764},
    {location:"Missoula, United States", latency:83.961},
    {location:"Monticello, United States", latency:37.532},
    {location:"Montreal, Canada", latency:22.359},
    {location:"Moscow, Russia", latency:150.768},
    {location:"Munich, Germany", latency:119.439},
    {location:"Nairobi, Kenya", latency:263.576},
    {location:"New Delhi, India", latency:343.81},
    {location:"New Orleans, United States", latency:30.75},
    {location:"New York, United States", latency:7.646},
    {location:"Newcastle, United Kingdom", latency:87.437},
    {location:"Novosibirsk, Russia", latency:198.383},
    {location:"Nuremberg, Germany", latency:102.655},
    {location:"Oklahoma City, United States", latency:40.591},
    {location:"Olney, United States", latency:10.468},
    {location:"Orlando, United States", latency:26.155},
    {location:"Osaka, Japan", latency:179.116},
    {location:"Oslo, Norway", latency:125.354},
    {location:"Palermo, Italy", latency:123.169},
    {location:"Panama, Panama", latency:76.964},
    {location:"Paris, France", latency:89.336},
    {location:"Perth, Australia", latency:367.921},
    {location:"Philadelphia, United States", latency:5.071},
    {location:"Phnom Penh, Cambodia", latency:292.963},
    {location:"Phoenix, United States", latency:74.188},
    {location:"Piscataway, United States", latency:7.261},
    {location:"Pittsburgh, United States", latency:7.802},
    {location:"Portland, United States", latency:76.028},
    {location:"Prague, Czech Republic", latency:114.28},
    {location:"Pristina, Kosovo", latency:141.902},
    {location:"Pune, India", latency:227.288},
    {location:"Raleigh, United States", latency:15.407},
    {location:"Redding, United States", latency:94.374},
    {location:"Reykjavik, Iceland", latency:124.019},
    {location:"Riga, Latvia", latency:119.792},
    {location:"Riyadh, Saudi Arabia", latency:243.656},
    {location:"Rome, Italy", latency:147.035},
    {location:"Roseburg, United States", latency:134.755},
    {location:"Rotterdam, Netherlands", latency:97.217},
    {location:"Roubaix, France", latency:83.726},
    {location:"Sacramento, United States", latency:71.194},
    {location:"Salem, United States", latency:15.048},
    {location:"Salt Lake City, United States", latency:64.591},
    {location:"San Antonio, United States", latency:50.211},
    {location:"San Diego, United States", latency:64.74},
    {location:"San Francisco, United States", latency:75.942},
    {location:"San Jose, United States", latency:91.631},
    {location:"San Juan, Puerto Rico", latency:57.815},
    {location:"Santiago, Chile", latency:128.149},
    {location:"Sao Paulo, Brazil", latency:208.725},
    {location:"Sapporo, Japan", latency:190.789},
    {location:"Saskatoon, Canada", latency:78.585},
    {location:"Scranton, United States", latency:11.102},
    {location:"Seattle, United States", latency:67.469},
    {location:"Secaucus, United States", latency:8.368},
    {location:"Seoul, South Korea", latency:192.365},
    {location:"Shanghai, China", latency:336.009},
    {location:"Shenzen, China", latency:244.17},
    {location:"Siauliai, Lithuania", latency:131.513},
    {location:"Singapore, Republic of Singapore", latency:245.057},
    {location:"Sofia, Bulgaria", latency:133.217},
    {location:"South Bend, United States", latency:21.708},
    {location:"St Louis, United States", latency:50.242},
    {location:"St Petersburg, Russia", latency:135.389},
    {location:"Stockholm, Sweden", latency:116.209},
    {location:"Strasbourg, France", latency:119.769},
    {location:"Sydney, Australia", latency:239.484},
    {location:"Taipei, Taiwan", latency:204.868},
    {location:"Tallinn, Estonia", latency:133.966},
    {location:"Tampa, United States", latency:95.165},
    {location:"Tel Aviv, Israel", latency:143.828},
    {location:"The Hague, Netherlands", latency:88.095},
    {location:"Thessaloniki, Greece", latency:147.733},
    {location:"Tijuana, Mexico", latency:73.782},
    {location:"Tirana, Albania", latency:141.131},
    {location:"Tokyo, Japan", latency:186.391},
    {location:"Toledo, United States", latency:20.166},
    {location:"Toronto, Canada", latency:22.021},
    {location:"Valencia, Spain", latency:113.882},
    {location:"Vancouver, Canada", latency:84.972},
    {location:"Varna, Bulgaria", latency:138.796},
    {location:"Venice, Italy", latency:105.376},
    {location:"Vienna, Austria", latency:120.9},
    {location:"Vilnius, Lithuania", latency:122.181},
    {location:"Vladivostok, Russia", latency:255.132},
    {location:"Warsaw, Poland", latency:136.694},
    {location:"Westpoort, Netherlands", latency:109.9},
    {location:"Wilmington, United States", latency:8.148},
    {location:"Winnipeg, Canada", latency:110.071},
    {location:"Zagreb, Croatia", latency:117.958},
    {location:"Zurich, Switzerland", latency:98.681}
];

db.sequelize.sync({force: true}).then(function() {
    data.forEach(function(obj, index) {
        setTimeout(function(){
            geocode(obj);
        }, index * 1000);
    });
});

function geocode(obj) {
    var uriEncodedPlace = obj.location.replace(" ", "+");
    var url = "https://maps.googleapis.com/maps/api/geocode/json?address=" + uriEncodedPlace + "&key=AIzaSyAzNbfObZ2JWVGV9EfApshy1hxETOLONlM";
    request(url, function (error, response, body) {
      if (!error && response.statusCode == 200) {
        var lat = JSON.parse(body).results[0].geometry.location.lat;
        var lng = JSON.parse(body).results[0].geometry.location.lng;
        var coordinates = { type: 'Point', coordinates: [lat, lng]};
        obj.coordinates = coordinates;

        var result = Result.build({});
        result.rtt = obj.latency;
        result.location = obj.coordinates;
        result.country = obj.location.split(', ')[1];

        reverseGeocode(result, function(err, result) {
            if (err) {
                console.warn("NO ADDRESS");
            }
            result.save();
        });
      }
    });
}
